Aplicaciones/qr/urls.py
from django.urls import path
from . import views
from django.conf.urls import handler404
from Aplicaciones.qr.views import error_404_view

app_name = "Aplicaciones"

urlpatterns = [
    path("", views.index, name="dashboard"),
    path("crear_evento/", views.crear_evento, name="crear_evento"),
    path("autent_qr/", views.autent_qr, name="autent_qr"),
    path("Inscripciones/", views.Inscripciones, name="Inscripciones"),
    path("event_creado/", views.event_creado, name="event_creado"),
   
    path("charts/", views.charts, name="charts"),
    path("signup/", views.signup, name="signup"),
    path("signin/", views.signin, name="signin"),
    path("signout/", views.signout, name="signout"),

]

sistemaContacto/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from Aplicaciones.qr import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Aplicaciones.qr.urls')),
    #path('signup/', views.signup, name='signup'), #registro
    #path('signout/', views.signout, name='signout'), # cerrar sesion
    #path('signin/', views.signin, name='signin'), # login

]

"""from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard', include('Aplicaciones.qr.urls'))
]

handler404 = 'Aplicaciones.qr.views.error_404_view'
"""

Aplicaciones/qr/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class user(models.Model):
    custom_id = models.AutoField(primary_key=True)
    cedula = models.CharField( max_length=10 )
    name = models.CharField(max_length=35)
    email = models.CharField(max_length=100)
    password = models.CharField(max_length=35)
    role = models.CharField(max_length=35)
    sexos = [
        ('F','Femenino'),
        ('M','Masculino')
    ]
    sex = models.CharField(max_length=1, choices=sexos, default='F')
    #fechaNacimiento = models.DateField()
    age = models.PositiveSmallIntegerField()
    country = models.CharField(max_length=35)
    city = models.CharField(max_length=35)
    address = models.CharField(max_length=35)
    phone = models.CharField(max_length=10)
    code_qr = models.CharField(max_length=35)
    #user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        texto = "{0} ({1})"
        return texto.format(self.name,self.cedula)
    

Aplicaciones/qr/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import user
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.utils import timezone
from django.contrib.auth.decorators import login_required


# Create your views here.

@login_required
def index(request):
    return render(request, 'dashboard/index.html')

@login_required
def Inscripciones(request):
    return render(request, 'dashboard/form_basic.html')

@login_required
def crear_evento(request):
    return render(request, "dashboard/crear-event.html")

@login_required
def autent_qr(request):
    return render(request, "dashboard/autent_qr.html")

@login_required
def event_creado(request):
    return render(request, "dashboard/event_creado.html")

@login_required
def charts(request):
    return render(request, "dashboard/charts.html")



#### views de Inicio de sesion ####

# REGISTRO
def signup(request):
    if request.method == 'GET':
        print('if')
        return render(request, 'dashboard/authentication-register.html', {"form": UserCreationForm})
    else:
        print('else')
        if request.POST["password1"] == request.POST["password2"]:
            try:
                usuario = User.objects.create_user(username=request.POST['username'],password=request.POST['password1'])
                usuario.save()
                login(request, usuario)
                return redirect('/')
            except IntegrityError:
                return render(request, 'dashboard/authentication-register.html', {
                    "form": UserCreationForm, 
                    "error": "Username already exists."})

        return render(request, 'dashboard/authentication-register.html', {
            "form": UserCreationForm, 
            "error": "Passwords did not match."})


# cerrrar sesion

@login_required
def signout(request):
    logout(request)
    return redirect('signin')

# login

def signin(request):
    if request.method == 'GET':
        return render(request, 'dashboard/authentication-login.html', {"form": AuthenticationForm})
    else:
        usuario = authenticate(
            request, username=request.POST['username'], password=request.POST['password'])
        if usuario is None:
            return render(request, 'dashboard/authentication-login.html', {"form": AuthenticationForm, "error": "Username or password is incorrect."})

        login(request, usuario)
        return redirect('/')




#error pagina no encontrada 
def error_404_view(request, exception):
    return render(request,'error_404.html')

templates/dashboard/charts.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}


{% block content %}

<div class="page-breadcrumb">
    <div class="row">
        <div class="col-12 d-flex no-block align-items-center">
            <h4 class="page-title" style="margin: 0 auto; float: none; width: 41%;">Dashboard Estadistico</h4>
            <div class="ml-auto text-right">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'Aplicaciones:dashboard' %}">Inicio</a></li>

                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/dashboard/crear-event.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}

{% block page_title %}
Form
{% endblock %}
{% block content %}
<div class="page-breadcrumb">
    <div class="row">
        <div class="col-12 d-flex no-block align-items-center">
            <h4 class="page-title" style="margin: 0 auto; float: none; width: 41%;">Creacion de Eventos</h4>
            <div class="ml-auto text-right">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'Aplicaciones:dashboard' %}">Inicio</a></li>

                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid">
    <!-- ============================================================== -->
    <!-- Start Page Content -->
    <!-- ============================================================== -->
    <div class="row">
        <div class="col-md-8" style="margin: 0 auto; float: none;">
            <div class="card">
                <form class="form-horizontal">
                    <div class="card-body">
                        <h4 class="card-title">Detalles del Evento</h4>
                        <div class="form-group row">
                            <label for="fname" class="col-sm-3 text-right control-label col-form-label">Nombre</label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control" id="fname" placeholder="Nombre del Evento">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="lname" class="col-sm-3 text-right control-label col-form-label">Ubicacion
                            </label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control" id="lname" placeholder="Ubicacion del Evento">
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="email1" class="col-sm-3 text-right control-label col-form-label">Tipo de
                                Evento</label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control" id="email1" placeholder="Tipo de Evento">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="lname" class="col-sm-3 text-right control-label col-form-label">Responsable
                            </label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control" id="lname"
                                    placeholder="Nombre del Responsable del Evento">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="lname" class="col-sm-3 text-right control-label col-form-label">Requisitos
                            </label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control" id="lname"
                                    placeholder="Requisitos para Ingresar al Evento">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="cono1" class="col-sm-3 text-right control-label col-form-label">Contacto
                                Inf</label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control phone-inputmask" id="phone-mask"
                                    placeholder="Numero de Contacto">
                            </div>

                        </div>

                        <div class="form-group row">
                            <label for="cono1" class="col-sm-3 text-right control-label col-form-label">Fecha
                            </label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control date-inputmask" id="date-mask"
                                    placeholder="Fecha del Evento">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="cono1" class="col-sm-3 text-right control-label col-form-label">Hora
                            </label>
                            <div class="col-sm-9">
                                <input type="time" class="form-control date-inputmask" id="time"
                                    placeholder="Hora del Evento">
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="cono1" class="col-sm-3 text-right control-label col-form-label">Cupos
                            </label>
                            <div class="col-sm-9">
                                <input type="Number" class="form-control" id="inputNumber" pattern="\d{1,3}"
                                    maxlength="3">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="cono1"
                                class="col-sm-3 text-right control-label col-form-label">Descripcion</label>
                            <div class="col-sm-9">
                                <textarea class="form-control"></textarea>
                            </div>
                        </div>

                    </div>
                    <div class="border-top" style="margin: 0 auto; float: none;"">
                        <div class=" card-body" style="margin: 0 auto; float: none; width: 50%;">
                        <button type="button" class="btn btn-primary">Crear</button>
                    </div>
            </div>
            </form>


        </div>

    </div>
</div>


{% endblock %}

templates/dashboard/event_creado.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}


{% block content %}
<div class="page-breadcrumb">
    <div class="row">
        <div class="col-12 d-flex no-block align-items-center">
            <h4 class="page-title">Eventos Creados</h4>
            <div class="ml-auto text-right">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'Aplicaciones:dashboard' %}">Inicio</a></li>

                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>


{% endblock %}

templates/dashboard/form_basic.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}

{% block page_title %}
Form
{% endblock %}
{% block content %}
<div class="page-breadcrumb">
    <div class="row">
        <div class="col-12 d-flex no-block align-items-center">
            <h4 class="page-title" style="margin: 0 auto; float: none; width: 41%;">Incripciones</h4>
            <div class="ml-auto text-right">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'Aplicaciones:dashboard' %}">Inicio</a></li>

                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid">
    <!-- ============================================================== -->
    <!-- Start Page Content -->
    <!-- ============================================================== -->
    <div class="row">
        <div class="col-md-8" style="margin: 0 auto; float: none;">
            <div class="card">
                <form class="form-horizontal">
                    <div class="card-body">
                        <h4 class="card-title">Formulario de inscripcion</h4>
                        <div class="form-group row">
                            <label for="fname" class="col-sm-3 text-right control-label col-form-label">Nombres</label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control" id="fname" placeholder="Ingrese sus Nombres">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="fname"
                                class="col-sm-3 text-right control-label col-form-label">Apellidos</label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control" id="fname" placeholder="Ingrese sus Apellidos">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="lname" class="col-sm-3 text-right control-label col-form-label">E-mail
                            </label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control" id="lname"
                                    placeholder="Ingrese su correo Electronico">
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="email1" class="col-sm-3 text-right control-label col-form-label">Ciudad
                            </label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control" id="email1" placeholder="Ingrese su Ciudad">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="lname" class="col-sm-3 text-right control-label col-form-label">Direccion
                            </label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control" id="lname" placeholder="Direccion Domiciliaria">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="lname" class="col-sm-3 text-right control-label col-form-label">Ocupacion
                            </label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control" id="lname" placeholder="Ingrese su Ocupacion">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="cono1" class="col-sm-3 text-right control-label col-form-label">Contacto
                            </label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control phone-inputmask" id="phone-mask"
                                    placeholder="Ingrese su numero Telefonico">
                            </div>


                        </div>
                        <div class="form-group row">
                            <label for="cono1" class="col-sm-3 text-right control-label col-form-label">Edad
                            </label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control" pattern="[0-9]{1,3}" maxlength="3" required
                                    placeholder="Ingrese su Edad">
                            </div>

                        </div>
                        <div class="form-group row">
                            <label for="cono1" class="col-sm-3 text-right control-label col-form-label">Genero</label>
                            <div class="col-md-9">
                                <div class="custom-control custom-radio">
                                    <input type="radio" class="custom-control-input" id="customControlValidation1"
                                        name="radio-stacked" required="">
                                    <label class="custom-control-label" for="customControlValidation1">Masculino
                                    </label>
                                </div>
                                <div class="custom-control custom-radio">
                                    <input type="radio" class="custom-control-input" id="customControlValidation2"
                                        name="radio-stacked" required="">
                                    <label class="custom-control-label" for="customControlValidation2">Femenino
                                    </label>
                                </div>
                                <div class="custom-control custom-radio">
                                    <input type="radio" class="custom-control-input" id="customControlValidation3"
                                        name="radio-stacked" required="">
                                    <label class="custom-control-label" for="customControlValidation3">Otros
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="cono1" class="col-sm-3 text-right control-label col-form-label">Discapacidad?
                            </label>
                            <div class="col-sm-9">
                                <div class="custom-control custom-radio">
                                    <select name="selectOption" id="selectOption" class="form-control">
                                        <option value="r">Si</option>
                                        <option value="a">No</option>
                                    </select>


                                </div>


                            </div>

                        </div>
                        <div class="form-group row">
                            <label for="cono1" class="col-sm-3 text-right control-label col-form-label">Asistira con
                                acompañante
                            </label>
                            <div class="col-sm-9">
                                <div class="custom-control custom-radio">
                                    <select name="selectOption" id="selectOption" class="form-control">
                                        <option value="r">Si</option>
                                        <option value="a">No</option>
                                    </select>
                                </div>
                            </div>

                        </div>

                        <div class="form-group row">
                            <label for="cono1" class="col-sm-3 text-right control-label col-form-label">Nivel Educativo
                            </label>
                            <div class="col-sm-9">
                                <div class="custom-control custom-radio">
                                    <select name="selectOption" id="selectOption" class="form-control">
                                        <option value="r">Primaria</option>
                                        <option value="a">Secundaria</option>
                                        <option value="a">Tercer Nivel</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="cono1" class="col-sm-3 text-right control-label col-form-label">¿Como se enteró
                                del evento?
                            </label>
                            <div class="col-sm-9">
                                <div class="custom-control custom-radio">
                                    <select name="selectOption" id="selectOption" class="form-control">
                                        <option value="r">Redes Sociales</option>
                                        <option value="a">Medios Impresos</option>
                                        <option value="a">Amigo</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="border-top" style="margin: 0 auto; float: none;"">
                        <div class=" card-body" style="margin: 0 auto; float: none; width: 50%;">
                        <button type="button" class="btn btn-primary">Crear</button>
                    </div>
            </div>
            </form>


        </div>

    </div>
</div>




{% endblock %}

templates/dashboard/includes/header.html
{% load static %}

<header class="topbar" data-navbarbg="skin5">
    <nav class="navbar fixed-top top-navbar navbar-expand-md navbar-dark">
        <div class="navbar-header" data-logobg="skin5">
            <!-- This is for the sidebar toggle which is visible on mobile only -->
            <a class="nav-toggler waves-effect waves-light d-block d-md-none" href="javascript:void(0)"><i
                    class="ti-menu ti-close"></i></a>
            <!-- ============================================================== -->
            <!-- Logo -->
            <!-- ============================================================== -->
            <a class="navbar-brand" href="{% url 'Aplicaciones:dashboard' %}">

                <!-- Logo text -->
                <b class="logo-icon p-l-40">
                    <!-- dark Logo text -->
                    <center><img src="{% static 'images/unemi.png' %}" alt="homepage" class="light-logo" height="50"
                            width="110" /></center>

                </b>

            </a>

            <!-- Toggle which is visible on mobile only -->
            <!-- ============================================================== -->
            <a class="topbartoggler d-block d-md-none waves-effect waves-light" href="javascript:void(0)"
                data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation"><i class="ti-more"></i></a>
        </div>
        <!-- ============================================================== -->
        <!-- End Logo -->
        <!-- ============================================================== -->
        <div class="navbar-collapse collapse" id="navbarSupportedContent" data-navbarbg="skin5">
            <!-- ============================================================== -->
            <!--alternar y elementos de navegacións -->
            <!-- ============================================================== -->
            <ul class="navbar-nav float-left mr-auto">
                <li class="nav-item d-none d-md-block"><a class="nav-link sidebartoggler waves-effect waves-light"
                        href="javascript:void(0)" data-sidebartype="mini-sidebar"><i
                            class="mdi mdi-menu font-24"></i></a></li>

            </ul>
            <!-- ============================================================== -->
            <!-- Cerrar Sesion -->
            <!-- ============================================================== -->
            <ul class="navbar-nav float-right">
                <!-- ============================================================== -->
                <li class="nav-item dropdown">
                    <a class="dropdown-item" href="javascript:void(0)"><i class="fa fa-power-off m-r-5 m-l-5"></i>
                        Cerrar Sesion</a>
                </li>
            </ul>
        </div>
    </nav>
</header>

templates/dashboard/includes/sidebar.html
{% load static %}

<aside class="left-sidebar scrollable ps-container ps-theme-default ps-active-y" data-sidebarbg="skin5">
    <!-- Sidebar scroll-->
    <div class="scroll-sidebar">
        <!-- Sidebar navigation-->
         <!-- Barra de navegacion vertical-->
        <nav class="sidebar-nav">
            <ul id="sidebarnav" class="p-t-30">
                <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link"
                        href="{% url 'Aplicaciones:dashboard' %}" aria-expanded="false"><i
                            class="mdi mdi-view-dashboard"></i><span class="hide-menu">Dashboard</span></a></li>
                <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link"
                        href="{% url 'Aplicaciones:charts' %}" aria-expanded="false"><i
                            class="mdi mdi-chart-bar"></i><span class="hide-menu">Dashboard Estadistico</span></a></li>

                <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link"
                        href="{% url 'Aplicaciones:crear_evento' %}" aria-expanded="false"><i
                            class="mdi mdi-pencil"></i><span class="hide-menu">Creacion de Eventos</span></a></li>

                <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link"
                        href="{% url 'Aplicaciones:event_creado' %}" aria-expanded="false"><i
                            class="mdi mdi-receipt"></i><span class="hide-menu">Eventos Creados</span></a></li>
                <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link"
                        href="{% url 'Aplicaciones:Inscripciones' %}" aria-expanded="false"><i
                            class="mdi mdi-arrow-all"></i><span class="hide-menu">Inscripciones</span></a></li>
                <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link"
                        href="{% url 'Aplicaciones:autent_qr' %}" aria-expanded="false"><i
                            class="mdi mdi-border-outside"></i><span class="hide-menu">Autentificacion QR</span></a>



            </ul>

            </ul>
        </nav>
        <!-- End Sidebar navigation -->
    </div>
    <!-- End Sidebar scroll-->
</aside>

templates/dashboard/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!-- ============================================================== -->
<!-- Bread crumb and right sidebar toggle -->
<!-- ============================================================== -->
<div class="page-breadcrumb">
    <div class="row">
        <div class="col-12 d-flex no-block align-items-center">
            <h4 class="page-title">Dashboard</h4>

        </div>
    </div>
</div>

<!-- Container fluid  -->
<!-- ============================================================== -->
<div class="container-fluid">
    <div class="row">
        <!-- Column -->
        <div class="col-md-6 col-lg-4 col-xlg-3">
            <div class="card card-hover">
                <div class="box bg-cyan text-center">
                    <h1 class="font-light text-white"><i class="mdi mdi-view-dashboard"></i></h1>
                    <h6 class="text-white">Dashboard</h6>
                </div>
            </div>
        </div>
        <!-- Column -->
        <div class="col-md-6 col-lg-4 col-xlg-3">
            <div class="card card-hover">
                <div class="box bg-success text-center">
                    <a href="{% url 'Aplicaciones:charts' %}">
                        <h1 class="font-light text-white"><i class="mdi mdi-chart-areaspline"></i></h1>
                        <h6 class="text-white">Dashboard Estadistico</h6>
                    </a>
                </div>
            </div>
        </div>
        <!-- Column -->
        <div class="col-md-6 col-lg-4 col-xlg-3">
            <div class="card card-hover">
                <div class="box bg-danger text-center">
                    <a href="{% url 'Aplicaciones:autent_qr' %}">
                        <h1 class="font-light text-white"><i class="mdi mdi-border-outside"></i></h1>
                        <h6 class="text-white">Autentificacion QR</h6>
                    </a>
                </div>
            </div>
        </div>
        <!-- Column -->
        <div class="col-md-6 col-lg-4 col-xlg-3">
            <div class="card card-hover">
                <div class="box bg-info text-center">
                    <a href="{% url 'Aplicaciones:Inscripciones' %}">
                        <h1 class="font-light text-white"><i class="mdi mdi-arrow-all"></i></h1>
                        <h6 class="text-white">Inscripciones</h6>
                    </a>
                </div>
            </div>
        </div>
        <!-- Column -->
        <div class="col-md-6 col-lg-4 col-xlg-3">
            <div class="card card-hover">
                <div class="box bg-danger text-center">
                    <a href="{% url 'Aplicaciones:event_creado' %}">
                        <h1 class="font-light text-white"><i class="mdi mdi-receipt"></i></h1>
                        <h6 class="text-white">Eventos Creados</h6>
                    </a>
                </div>
            </div>
        </div>
        <!-- Column -->
        <div class="col-md-6 col-lg-4 col-xlg-3">
            <div class="card card-hover">
                <div class="box bg-cyan text-center">
                    <a href="{% url 'Aplicaciones:crear_evento' %}">
                        <h1 class="font-light text-white"><i class="mdi mdi-pencil"></i></h1>
                        <h6 class="text-white">Creacion de Eventos</h6>
                    </a>
                </div>
            </div>
        </div>

    </div>

</div>

{% endblock content %}